version: "3"
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://server:4000
    networks:
      - mynetwork

  server:
    build:
      context: ./server
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    networks:
      - mynetwork

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    networks:
      - mynetwork

networks:
  mynetwork:
